### ISSUE TITLE
easier dependencies

### ISSUE THREAD

**Issue by gedw99** [anthonynsimon/parrot#28]
It will be very easy to change the db to QL or BoltDB.
It will make the code and deployment, management much simpler i feel.
QL is a SQL db.  
BoltDB is a Key value store db.

Both are 100% golang based databases.

QL
https://godoc.org/github.com/cznic/ql
- an ORM for QL: https://github.com/gernest/ngorm

BoltDB
https://github.com/boltdb/bolt
- an ORM for BoltDB: https://github.com/asdine/storm

is this something your open to ?

**Comment by anthonynsimon** [comment]
Definitely! The DB layer has been already abstracted in a way so that any database, as long as it implements the "datastore.Store" interface, it should work. 

The only thing is that at the moment there are no automated tests for the datastore package, something which should also be solved sometime in the near future, so at the moment it will require some manual testing.

Again, feel free to work on any implementation, contributions are more than welcome!

**Comment by gedw99** [comment]
Great news. I will be making some PR's

**Comment by anthonynsimon** [comment]
Cool, just open them once you've got some progress.
