### ISSUE TITLE
Do not enforce SSL

### ISSUE THREAD

**Issue by tboerger** [anthonynsimon/parrot#38]
Please provide HTTPS only optionally, most container-based scenarios are doing SSL termination on an reverse proxy and continue with HTTP to the application. Beside that I personally don't generate any certificates on my own anymore, everything is handled by Let's Encrypt.

Maybe it's also an option to integrate Let's Encrypt for the other cases natively, I have already done that for other projects like https://github.com/kleister/kleister-api/blob/master/cmd/server.go#L214-L272

**Comment by anthonynsimon** [comment]
Thanks for the suggestion, makes sense, an option to serve over HTTP instead of HTTPS can be added. 

There has been some discussion regarding the SSL termination once it reaches the reverse proxy, apparently there was some attack at Google that exploited exactly that for some servers. Since the auth tokens rely on the assumption that the connection is encrypted from the browser to the API server, I would still leave HTTPS as the default option and maybe use something like Let's Encrypt at some point.

**Comment by anthonynsimon** [comment]
After considering the pros and cons of your proposal, we're removing the SSL enforcement on the API server, but leaving it on the provided reverse-proxy. This way deployment is now easier and more open to various configurations. 

Nonetheless, it is still strongly recommended to deploy it with a secure reverse-proxy or equivalent solution in front of the API.
