### ISSUE TITLE
Suggestion: Embed the migrations

### ISSUE THREAD

**Issue by tboerger** [anthonynsimon/parrot#41]
I want to suggest to embedd the migrations, with tools like go-bindata or something similar it's quite easy to avoid the need of deploying additional files with the single binary.

**Comment by anthonynsimon** [comment]
Makes sense, will take a look into it :)

**Comment by anthonynsimon** [comment]
#80 removes the migrations from the API binary, it will be handled by Alembic.

**Comment by tboerger** [comment]
Ok, the decision is up to you... But seriously a python library for doing database migrations for a golang project? Sounds more than strange :D

**Comment by anthonynsimon** [comment]
I can understand it seems strange :) This is more of an interim solution to get out the migrations from the binary, until a better solution comes.

Although it's not strictly a Go project, most likely it will undergo major restructuring before v1.0 in order to accommodate the missing features and help ease development.

**Comment by tboerger** [comment]
But there are pretty good migration utils available for go and it's pretty common to embed things like that to keep deployments as easy as possible ;)

**Comment by tboerger** [comment]
I like the idea of this project and I had interest to contribute but this gets a structure I'm personally not feeling comfortable with. Sadly I'm out :)

**Comment by anthonynsimon** [comment]
No worries, thanks anyways for your suggestions!
