### ISSUE TITLE
net::ERR_INSECURE_RESPONSE on Register

### ISSUE THREAD

**Issue by StanBoyet** [anthonynsimon/parrot#42]
Hi,

On development, after saying to Chrome that yes, I trust this untrusful website (don't have certificates), I can't register because of this error:

![screen shot 2017-02-27 at 10 41 33](https://cloud.githubusercontent.com/assets/1906401/23356401/f0040182-fcd9-11e6-829c-2c94c2a740e0.png)

I guess it's related to the fact that I don't truly have an HTTPS connection set up. How could I bypass this ?

Thanks

**Comment by anthonynsimon** [comment]
Hi! At the moment we haven't implemented support for non-HTTPS connections since the authentication tokens rely on such a connection. But the option to serve over regular HTTP will come at some point.

But even so, currently the API server takes care of generating self-signed certificates for development and testing purposes, so it should work out of the box. Are you running everything via Docker and using the provided deployment scripts?
