### ISSUE TITLE
ping 404 response

### ISSUE THREAD

**Issue by tqcenglish** [anthonynsimon/parrot#48]
when `go build` on different directory ,  custom directory have a error
```
ip=127.0.0.1:52250 latency=73.828µs method=GET status=404 url=/api/v1/p
ing
```
but in `src/github.com/anthonynsimon/parrot/parrot-api` is worked.

**Comment by anthonynsimon** [comment]
That's because the API which is written in Go, is located at the parrot-api directory. You should built on the right directory, `src/github.com/anthonynsimon/parrot/parrot-api`. Additionally, you might want to take a look at the build scripts that are included, for any additional build steps that you might require.
